### ISSUE TITLE
System for booking appointments (EPIC)

### ISSUE THREAD

**Issue by msgregorsamsa** [sannawiklund/HealthCareAB#8]
Below are all the points regarding the content and functionality of the booking page. These will be done as separate issues.

Booking, frontend
- [ ] Booking page: Consistent styling of the page
- [ ] Booking page: Add buttons, timetable and ability to chose type of caregiver
- [ ] Booking page: Create accessible html

Booking, backend
- [ ] Booking page: Get available appointments and care givers via API from the database.
- [ ] Booking page: Redirect to confirmation page when done
- [ ] Booking page: Recieve confirmation through email or text-message.
